[oracle]
username = username
password = password
wallet_path = /opt/oracle/wallet
wallet_password = password
dsn = (description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.eu-frankfurt-1.oraclecloud.com))(connect_data=(service_name=ge00000000000ce_gloodata_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
schema = SH
